Stop falling back to WASM sane-fmt
WASM sane-fmt doesn't exist here

diff --git a/run-on-save b/run-on-save
--- a/run-on-save
+++ b/run-on-save
@@ -27,16 +27,16 @@
 set -o errexit -o pipefail -o nounset
 
 # TASK: Use sane-fmt to format TypeScript/JavaScript file
-# Recommend: Install native sane-fmt for good performance (https://github.com/sane-fmt/sane-fmt)
+# <https://github.com/sane-fmt/sane-fmt>
 for ext in js ts jsx tsx; do
   if [[ "$FILE" == *.$ext && "$FILE" != *node_modules* ]]; then
     if which sane-fmt &>/dev/null; then
       echo "Run sane-fmt on $FILE"
       sane-fmt --color=never --write "$FILE"
     else
-      echo 'Using WebAssembly implementation of sane-fmt'
-      echo 'Recommend: Install native version from https://github.com/sane-fmt/sane-fmt'
-      pnpm run sane-fmt:fix -- --color=never --hide-passed
+      echo 'Fail to detect sane-fmt in PATH'
+      echo 'See <https://github.com/sane-fmt/sane-fmt> for installation instruction'
+      exit 1
     fi
     break
   fi
